version: "3"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=admin
      # - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - ${PWD}/certs/server.crt:/var/lib/postgresql/server.crt:ro
      - ${PWD}/certs/server.key:/var/lib/postgresql/server.key:ro
    ports:
      - 5432:5432
  db_ns:
    image: postgres:latest
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=admin
      # - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

networks:
  default:
    name: api_net
