api:
  test: "api_test"
db:
  url: "host=db user=postgres password=admin port=5432 sslmode=disable"
  url_host: "host=localhost user=postgres password=admin port=5432 sslmode=require dbname=api"
  test: "db_test"
